name: Run Azure to Redmine Sync Script

on:
  workflow_dispatch:
    inputs:
      sprintNumber:
        description: 'Sprint Number (leave blank to use default)'
        required: false
  schedule:
    # Horario Estándar (CET, UTC+1) - Activo
    # De lunes a jueves, cada 15 minutos desde las 7:00 hasta las 17:00 UTC (8:00 a 18:00 CET)
    - cron: '*/15 7-16 * * 1-4'
    # Los viernes, cada 15 minutos desde las 7:00 hasta las 15:00 UTC (8:00 a 16:00 CET)
    - cron: '*/15 7-14 * * 5'

    # Horario de Verano (CEST, UTC+2) - Comentado
    # Descomenta las siguientes líneas durante el horario de verano
    # De lunes a jueves, cada 15 minutos desde las 6:00 hasta las 16:00 UTC (8:00 a 18:00 CEST)
    # - cron: '*/15 6-15 * * 1-4'
    # Los viernes, cada 15 minutos desde las 6:00 hasta las 14:00 UTC (8:00 a 16:00 CEST)
    # - cron: '*/15 6-13 * * 5'

jobs:
  execute-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # - name: Install wkhtmltopdf
      #   run: |
      #     sudo apt-get update -y
      #     sudo apt-get install -y wkhtmltopdf

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set Environment Variables
        run: |
          echo "AZURE_DEVOPS_PROJECT_BASE=${{ secrets.AZURE_DEVOPS_PROJECT_BASE }}" >> $GITHUB_ENV
          echo "AZURE_TEAM=${{ secrets.AZURE_TEAM }}" >> $GITHUB_ENV
          echo "AZURE_TOKEN=${{ secrets.AZURE_TOKEN }}" >> $GITHUB_ENV
          echo "AREA_PATH=${{ secrets.AREA_PATH }}" >> $GITHUB_ENV
          echo "ITERATION_PATH=${{ secrets.ITERATION_PATH }}" >> $GITHUB_ENV
          echo "REDMINE_URL=${{ secrets.REDMINE_URL }}" >> $GITHUB_ENV
          echo "REDMINE_TOKEN=${{ secrets.REDMINE_TOKEN }}" >> $GITHUB_ENV
          echo "PROJECT_ID=${{ secrets.PROJECT_ID }}" >> $GITHUB_ENV
          echo "ID_CAMPO_HORAS_RESTANTES=${{ secrets.ID_CAMPO_HORAS_RESTANTES }}" >> $GITHUB_ENV
          echo "ID_CAMPO_IBER_IDCLIENTE=${{ secrets.ID_CAMPO_IBER_IDCLIENTE }}" >> $GITHUB_ENV
          echo "SMTP_SERVER=${{ secrets.SMTP_SERVER }}" >> $GITHUB_ENV
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> $GITHUB_ENV
          echo "SMTP_USER=${{ secrets.SMTP_USER }}" >> $GITHUB_ENV
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> $GITHUB_ENV
          echo "WKHTMLTOPDF_PATH=${{ secrets.WKHTMLTOPDF_PATH }}" >> $GITHUB_ENV

      - name: Determine Sprint Number
        run: |
          if [ -z "${{ github.event.inputs.sprintNumber }}" ]; then
            echo "Using default sprint number"
            echo "SPRINT_NUMBER=${{ secrets.DEFAULT_SPRINT_NUMBER }}" >> $GITHUB_ENV
          else
            echo "Using provided sprint number"
            echo "SPRINT_NUMBER=${{ github.event.inputs.sprintNumber }}" >> $GITHUB_ENV
          fi
        shell: bash
    
      - name: Run the script
        run: python azure_to_redmine_sync.py $SPRINT_NUMBER

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v2
        with:
          name: generated-pdf
          path: resumen_ejecucion.pdf
